namespace Hi3Helper.Win32.Native.Enums.D2D;

public enum DWRITE_MEASURING_MODE
{
    DWRITE_MEASURING_MODE_NATURAL = 0,
    DWRITE_MEASURING_MODE_GDI_CLASSIC = 1,
    DWRITE_MEASURING_MODE_GDI_NATURAL = 2,
}