namespace Hi3Helper.Win32.Native.Enums;

public enum TASK_SESSION_STATE_CHANGE_TYPE
{
    TASK_CONSOLE_CONNECT = 1,
    TASK_CONSOLE_DISCONNECT,
    TASK_REMOTE_CONNECT,
    TASK_REMOTE_DISCONNECT,
    TASK_SESSION_LOCK = 7,
    TASK_SESSION_UNLOCK
}