namespace Hi3Helper.Win32.Native.Enums.D3D;

public enum D3D11_CONSERVATIVE_RASTERIZATION_MODE
{
    D3D11_CONSERVATIVE_RASTERIZATION_MODE_OFF = 0,
    D3D11_CONSERVATIVE_RASTERIZATION_MODE_ON = 1,
}
